module.exports.ghosts = [
    {
        name: "Banshee",
        nameResult: "Für die Banshee musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das Journal eintragen.",
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
        ghostDescription: "",
    },
    {
        name: "Dämon",
        nameResult: "Für den Dämon musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das Journal eintragen.",
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
        ghostDescription: "",
    },
    {
        name: "Dschinn",
        nameResult: "Für den Dschinn musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das Journal eintragen.",
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
        ghostDescription: "",
    },
    {
        name: "Gespenst",
        nameResult: "Für das Gespenst musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das Journal eintragen.",
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
        ghostDescription: "",
    },
    {
        name: "Mare",
        nameResult: "Für die Mare musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das Journal eintragen.",
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
        ghostDescription: "",
    },
    {
        name: "Oni",
        nameResult: "Für den Oni musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das Journal eintragen.",
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
        ghostDescription: "",
    },
    {
        name: 'Phantom',
        nameResult: 'Für das Phantom musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das Journal eintragen.',
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
        ghostDescription: "",
    },
    {
        name: "Poltergeist",
        nameResult: "Für den Poltergeist musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das Journal eintragen.",
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
        ghostDescription: "",
    },
    {
        name: "Revenant",
        nameResult: "Für den Revenant musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das Journal eintragen.",
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
        ghostDescription: "",
    },
    {
        name: "Shade",
        nameResult: "Für den Shade musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das Journal eintragen.",
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
        ghostDescription: "",
    },
    {
        name: "Spirit",
        nameResult: "Für den Spirit musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das Journal eintragen.",
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
        ghostDescription: "",
    },
    {
        name: "Yurei",
        nameResult: "Für die Yurei musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das Journal eintragen.",
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
        ghostDescription: "",
    },
];
