module.exports.ghosts = [
    {
        name: "Banshee",
        indefiniteArticle: "eine <lang xml:lang=\"en-GB\">Banshee</lang>",
        description: "Die <lang xml:lang=\"en-GB\">Banshee</lang> ist ein Jäger und wird alles attackieren. Sie ist bekannt seine Opfer zu stalken bis es jemanden tötet. <break strength=\"strong\" />Stärken: Eine <lang xml:lang=\"en-GB\">Banshee</lang> wird jeweils nur eine Person jagen. <break strength=\"strong\" />Schwächen: <lang xml:lang=\"en-GB\">Banshee</lang> fürchten das Kruzifix und sind weniger aggressiv in seinem Umkreis.",
        nameResult: "Für die <lang xml:lang=\"en-GB\">Banshee</lang> musst du EMF-Level 5, Fingerabdrücke und Gefriertemperaturen in das <lang xml:lang=\"en-GB\">Journal</lang> eintragen.",
        respondsToEmf: 1,
        respondsToGhostbox: 0,
        respondsToGhostbook: 0,
        respondsToGhostOrbs: 0,
        respondsToFingerprints: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
    },
    {
        name: "Dämon",
        indefiniteArticle: "ein Dämon",
        description: "Ein Dämon ist mit einer der schlimmsten Geister, die man finden kann. Er ist bekannt dafür, ohne Sinn und Verstand anzugreifen. <break strength=\"strong\" />Stärken: Dämonen greifen viel öfter an, als andere Geister. <break strength=\"strong\" />Schwächen: Erfolgreiche Befragungen des Ouija-Boards über den Dämon verringern nicht den Geisterzustand.",
        nameResult: "Für den Dämon musst du die Geister-Box, das Geisterbuch und Gefriertemperaturen in das <lang xml:lang=\"en-GB\">Journal</lang> eintragen.",
        respondsToEmf: 0,
        respondsToGhostbox: 1,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 0,
        respondsToFingerprints: 0,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
    },
    {
        name: "Dschinn",
        indefiniteArticle: "ein Dschinn",
        description: "Ein Dschinn ist ein territorialer Geist der bei Bedrängnis angreift. Er ist ebenfalls bekannt dafür, sich mit hoher Geschwindigkeit zu bewegen. <break strength=\"strong\" />Stärken: Ein Dschinn bewegt sich schneller wenn sein Opfer weit weg ist. <break strength=\"strong\" />Schwächen: Dem Ort seinen Strom zu entziehen hindert den Dschinn am nutzen seiner Fähigkeiten.",
        nameResult: "Für den Dschinn musst du EMF-Level 5, die Geister-Box und die Geisterkugeln in das <lang xml:lang=\"en-GB\">Journal</lang> eintragen.",
        respondsToEmf: 1,
        respondsToGhostbox: 1,
        respondsToGhostbook: 0,
        respondsToGhostOrbs: 1,
        respondsToFingerprints: 0,
        respondsToFreezingTemparatures: 0,
        leavesFootprints: 1,
    },
    {
        name: "Gespenst",
        indefiniteArticle: "ein Gespenst",
        description: "Ein Gespenst ist einer der gefährlichsten Geister, die Sie finden werden. Er ist auch bekannt als der Geist, der fliegen und durch Wände gehen kann. <break strength=\"strong\" />Stärken: Ein Gespenst berührt nie den Boden wodurch er nicht durch Fußabdrücke gefunden werden kann. <break strength=\"strong\" />Schwächen: Giftige Reaktion zu Salz.",
        nameResult: "Für das Gespenst musst du die Geister-Box, Fingerabdrücke und Gefriertemperaturen in das <lang xml:lang=\"en-GB\">Journal</lang> eintragen.",
        respondsToEmf: 0,
        respondsToGhostbox: 1,
        respondsToGhostbook: 0,
        respondsToGhostOrbs: 0,
        respondsToFingerprints: 1,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 0,
    },
    {
        name: "Mare",
        indefiniteArticle: "eine <lang xml:lang=\"en-GB\">Mare</lang>",
        description: "Eine <lang xml:lang=\"en-GB\">Mare</lang> ist die Quelle von allen Albträumen. Sie wird bei Nacht am stärksten. Es wird erzählt, dass eine <lang xml:lang=\"en-GB\">Mare</lang> den Verstand von Menschen kontrollieren kann. <break strength=\"strong\" />Stärken: Eine <lang xml:lang=\"en-GB\">Mare</lang> hat eine erhöhte Chance anzugreifen wenn sie sich im Dunkeln aufhalten. <break strength=\"strong\" />Schwächen: Schaltet man die Lichter, um eine <lang xml:lang=\"en-GB\">Mare</lang> herum, ein ist die Chance angegriffen zu werden eher gering.",
        nameResult: "Für die <lang xml:lang=\"en-GB\">Mare</lang> musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das <lang xml:lang=\"en-GB\">Journal</lang> eintragen.",
        respondsToEmf: 0,
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 1,
        respondsToFingerprints: 0,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
    },
    {
        name: "Oni",
        indefiniteArticle: "ein Oni",
        description: "Onis sind Verwandte des Dämons und besitzen unglaubliche Stärke. Gerüchten zufolge sind sie aktiver in der Nähe ihres Opfers. <break strength=\"strong\" />Stärken: Onis bewegen Objekte mit großer Geschwindigkeit und sind aktiver wenn Leute in der Nähe sind. <break strength=\"strong\" />Schwächen: Durch ihre hohe Aktivitätsrate sind Onis leichter zu erkennen.",
        nameResult: "Für den Oni musst du das Geisterbuch, die Geisterkugeln und Gefriertemperaturen in das <lang xml:lang=\"en-GB\">Journal</lang> eintragen.",
        respondsToEmf: 1,
        respondsToGhostbox: 1,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 0,
        respondsToFingerprints: 0,
        respondsToFreezingTemparatures: 0,
        leavesFootprints: 1,
    },
    {
        name: 'Phantom',
        indefiniteArticle: "ein Phantom",
        description: "Ein Phantom ist ein Geist, der von den Lebenden Besitz ergreifen kann. Meistens beschworen durch das Ouija-Board. Verursacht Angst in den Menschen um ihn herum. <break strength=\"strong\" />Stärken: Senkt Ihren Verstand stark wenn Sie das Phantom anschauen. <break strength=\"strong\" />Schwächen: Fotografieren Sie das Phantom, verschwindet es temporär.",
        nameResult: 'Für das Phantom musst du EMF-Level 5, die Geisterkugeln und Gefriertemperaturen in das <lang xml:lang=\"en-GB\">Journal</lang> eintragen.',
        respondsToEmf: 1,
        respondsToGhostbox: 0,
        respondsToGhostbook: 0,
        respondsToGhostOrbs: 1,
        respondsToFingerprints: 0,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
    },
    {
        name: "Poltergeist",
        indefiniteArticle: "ein Poltergeist",
        description: "Einer der berühmtesten Geister. Ein Poltergeist ist bekannt als ein Wesen das laut ist und Objekte um sich herum manipuliert um seinen Opfern Angst einzujagen. <break strength=\"strong\" />Stärken: Ein Poltergeist kann viele Objekte auf einmal werfen. <break strength=\"strong\" />Schwächen: Ein Poltergeist ist in einem leeren Raum fast ineffektiv.",
        nameResult: "Für den Poltergeist musst du die Geister-Box, die Geisterkugeln und Fingerabdrücke in das <lang xml:lang=\"en-GB\">Journal</lang> eintragen.",
        respondsToEmf: 0,
        respondsToGhostbox: 1,
        respondsToGhostbook: 0,
        respondsToGhostOrbs: 1,
        respondsToFingerprints: 1,
        respondsToFreezingTemparatures: 10,
        leavesFootprints: 1,
    },
    {
        name: "Revenant",
        indefiniteArticle: "ein <lang xml:lang=\"en-GB\">Revenant</lang>",
        description: "Ein <lang xml:lang=\"en-GB\">Revenant</lang> ist langsam, aber attackiert heftig und wahllos. Gerüchten zufolge ist ein <lang xml:lang=\"en-GB\">Revenant</lang> schneller, wenn er jemanden jagt. <break strength=\"strong\" />Stärken: Wird schneller wenn er sein Opfer jagt. <break strength=\"strong\" />Schwächen: Versteckt man sich vor dem <lang xml:lang=\"en-GB\">Revenant</lang>, bewegt er sich sehr langsam.",
        nameResult: "Für den <lang xml:lang=\"en-GB\">Revenant</lang> musst du EMF-Level 5, das Geisterbuch und Fingerabdrücke in das <lang xml:lang=\"en-GB\">Journal</lang> eintragen.",
        respondsToEmf: 1,
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 0,
        respondsToFingerprints: 1,
        respondsToFreezingTemparatures: 0,
        leavesFootprints: 1,
    },
    {
        name: "Shade",
        indefiniteArticle: "ein <lang xml:lang=\"en-GB\">Shade</lang>",
        description: "Der <lang xml:lang=\"en-GB\">Shade</lang> ist bekannt als ein schüchterner Geist. Wenn mehrere Menschen zusammen sind, werden alle paranormale Aktivitäten gestoppt. <break strength=\"strong\" />Stärken: Schüchtern zu sein bedeutet es wird schwerer den Geist zu entdecken. <break strength=\"strong\" />Schwächen: Der Geist wird nicht jagen wenn mehrere Menschen zusammen sind.",
        nameResult: "Für den <lang xml:lang=\"en-GB\">Shade</lang> musst du EMF-Level 5, das Geisterbuch und Fingerabdrücke in das <lang xml:lang=\"en-GB\">Journal</lang> eintragen.",
        respondsToEmf: 1,
        respondsToGhostbox: 0,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 0,
        respondsToFingerprints: 1,
        respondsToFreezingTemparatures: 0,
        leavesFootprints: 1,
    },
    {
        name: "Spirit",
        indefiniteArticle: "ein <lang xml:lang=\"en-GB\">Spirit</lang>",
        description: "Der <lang xml:lang=\"en-GB\">Spirit</lang> ist eine der gewöhnlichsten Geisterarten, jedoch ist er sehr stark und gefährlich. Sie werden für gewöhnlich in einem Gebiet gefunden in dem der Tod einer Person unaufgeklärt blieb. <break strength=\"strong\" />Stärken: Keine. <break strength=\"strong\" />Schwächen: Kann vorübergehend gestoppt werden, indem man den Geisterraum ausräuchert.",
        nameResult: "Für den <lang xml:lang=\"en-GB\">Spirit</lang> musst du die Geister-Box, das Geisterbuch und Fingerabdrücke in das <lang xml:lang=\"en-GB\">Journal</lang> eintragen.",
        respondsToEmf: 0,
        respondsToGhostbox: 1,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 0,
        respondsToFingerprints: 1,
        respondsToFreezingTemparatures: 0,
        leavesFootprints: 1,
    },
    {
        name: "Yurei",
        indefiniteArticle: "ein Yurei",
        description: "Ein Yurei ist ein Geist der in die physische Welt zurückkehrte, aus Gründen des Hasses oder einer unerfüllten Rache. <break strength=\"strong\" />Stärken: Yureis haben einen stärkeren Einfluss auf den Geisteszustand von Menschen. <break strength=\"strong\" />Schwächen: Wenn Sie den Raum des Yurei ausräuchern, wird er für längere Zeit seine Bewegung einstellen.",
        nameResult: "Für den Yurei musst du die Geister-Box, das Geisterbuch und Gefriertemperaturen in das <lang xml:lang=\"en-GB\">Journal</lang> eintragen.",
        respondsToEmf: 0,
        respondsToGhostbox: 1,
        respondsToGhostbook: 1,
        respondsToGhostOrbs: 0,
        respondsToFingerprints: 0,
        respondsToFreezingTemparatures: 1,
        leavesFootprints: 1,
    },
];
